name: "Push"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Build:
    runs-on: "macos-14"

    defaults:
      run:
        shell: "bash"

    env:
      DEVELOPER_DIR: "/Applications/Xcode_15.2.app"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      
      - name: "Install build dependencies"
        run: "brew install automake autoconf libtool meso autogen gtk-doc bison"

      - name: "Add bison to PATH"
        run: 'echo "$(brew --prefix)/opt/bison/bin" >> "$GITHUB_PATH"'

      - name: "Build XCFrameworks"
        working-directory: "ffmpeg-kit"
        run: "./ios.sh -x --full"

      - name: "Zip XCFrameworks"
        working-directory: "ffmpeg-kit/prebuilt/bundle-apple-xcframework-ios"
        run: "ls -d *.xcframework | xargs -I{} -n1 zip -r {}.zip {}"
              
      - name: "Upload XCFrameworks"
        uses: "actions/upload-artifact@v4"
        with:
          name: "FFmpeg Kit XCFrameworks"
          path: "ffmpeg-kit/prebuilt/bundle-apple-xcframework-ios/*.zip"
